baseurl = "/"
languageCode = "en-us"
title = "Menagerie"
theme = "hugo-classic"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
enableEmoji = true
footnotereturnlinkcontents = "↩"

[permalinks]
    # post = "/post/:year/:month/:day/:slug/"
    posts = "/:filename"

[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 1
# [[menu.main]]
#     name = "Tags"
#     url = "/tags/"
#     weight = 2
# [[menu.feed]]
#     name = "Subscribe"
#     url = "/index.xml"

[params]
    description = "This is the place where I write about things I don't understand, I think I don't understand, I think I will never understand, and I'm certain I'll never understand. And the occasional piece on things I do understand."
    footer = "*Fortitudine Vincimus* == [Ernest Shackleton](https://en.wikipedia.org/wiki/Ernest_Shackleton) is rad."
    custom_css = ["css/theme-override.css"]
